name: YTMonster Login and Launch Client Workflow

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:

jobs:
  login-job:
    runs-on: ubuntu-latest

    env:
      YTMONSTER_USERNAME: ${{ secrets.YTMONSTER_USERNAME }}
      YTMONSTER_PASSWORD: ${{ secrets.YTMONSTER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Initializing npm project..."
          npm init -y
          echo "Installing puppeteer-real-browser..."
          npm install puppeteer-real-browser

      - name: System information
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "System info: $(uname -a)"
          echo "Available memory: $(free -h)"
          echo "Available disk space: $(df -h)"
          echo "Network connection: $(curl -s https://www.google.com > /dev/null && echo 'Connected' || echo 'Disconnected')"

      - name: Create script and screenshots directories
        run: |
          mkdir -p scripts
          mkdir -p screenshots

      - name: Create YTMonster Login and Launch Script
        run: |
          echo "Generating login and launch client script..."
          cat > scripts/ytmonster-login.js << 'EOL'
          const { connect } = require('puppeteer-real-browser');
          const fs = require('fs');
          const path = require('path');

          (async () => {
            // Define the screenshots directory relative to repository root.
            const screenshotsDir = path.join(__dirname, '../screenshots');
            if (!fs.existsSync(screenshotsDir)) {
              fs.mkdirSync(screenshotsDir, { recursive: true });
            }

            // Retrieve credentials from environment variables.
            const username = process.env.YTMONSTER_USERNAME;
            const password = process.env.YTMONSTER_PASSWORD;
            if (!username || !password) {
              console.error("Missing credentials! Ensure YTMONSTER_USERNAME and YTMONSTER_PASSWORD are set.");
              process.exit(1);
            }

            // Connect to a real browser instance using puppeteer-real-browser.
            // '--disable-popup-blocking' ensures pop-ups are not blocked.
            const { browser, page } = await connect({
              headless: true,
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1280,800',
                '--disable-popup-blocking'
              ],
              customConfig: {
                defaultViewport: { width: 1280, height: 800 }
              },
              turnstile: true,
            });

            try {
              // STEP 1: Navigate to the login page.
              console.log("Navigating to https://www.ytmonster.net/exchange/views ...");
              await page.goto("https://www.ytmonster.net/exchange/views", { waitUntil: "domcontentloaded", timeout: 60000 });
              await page.screenshot({ path: path.join(screenshotsDir, "step1_navigate.png"), fullPage: true });

              // STEP 2: Wait for login form.
              console.log("Waiting for login form elements...");
              await page.waitForSelector('#inputUsername', { visible: true, timeout: 30000 });
              await page.waitForSelector('#inputPassword', { visible: true, timeout: 30000 });
              await page.screenshot({ path: path.join(screenshotsDir, "step2_login_form_loaded.png"), fullPage: true });

              // STEP 3: Fill in credentials.
              console.log("Filling in credentials...");
              await page.type('#inputUsername', username, { delay: 100 });
              await page.type('#inputPassword', password, { delay: 100 });
              await page.screenshot({ path: path.join(screenshotsDir, "step3_credentials_filled.png"), fullPage: true });

              // STEP 4: Click the login button.
              console.log("Submitting the login form...");
              await page.waitForSelector("button[type='submit']", { visible: true, timeout: 30000 });
              await page.click("button[type='submit']");
              await page.screenshot({ path: path.join(screenshotsDir, "step4_after_submit_click.png"), fullPage: true });

              // STEP 5: Wait for login success.
              console.log("Waiting for login success...");
              try {
                await page.waitForNavigation({ waitUntil: "domcontentloaded", timeout: 30000 });
              } catch (navError) {
                console.warn("Navigation did not occur; checking for login form disappearance.");
              }
              await page.waitForFunction(() => !document.querySelector("#formLogin"), { timeout: 30000 });
              await page.screenshot({ path: path.join(screenshotsDir, "step5_logged_in.png"), fullPage: true });
              console.log("Login successful.");

              // NEW STEP: End All Sessions
              console.log("Ending all sessions by clicking 'End All Sessions' button...");
              await page.waitForSelector('#endAll', { visible: true, timeout: 30000 });
              await page.click('#endAll');
              await page.screenshot({ path: path.join(screenshotsDir, "step5_end_all_sessions.png"), fullPage: true });
              console.log("All sessions ended.");

              // STEP 6: Launch the client.
              console.log("Clicking the Launch Client button...");
              await page.waitForSelector("a.open-client", { visible: true, timeout: 30000 });
              
              const newPagePromise = new Promise(resolve => {
                browser.once('targetcreated', async target => {
                  if (target.type() === 'page') {
                    console.log("New target of type 'page' detected. Retrieving client page...");
                    const newPage = await target.page();
                    console.log("Client page successfully retrieved.");
                    resolve(newPage);
                  }
                });
              });

              await page.click("a.open-client");
              console.log("Launch Client button clicked. Waiting for client page to open...");

              const clientPage = await newPagePromise;
              console.log("Client page opened.");

              // Attempt a brief wait for navigation (5s).
              console.log("Checking for navigation event on the client page for 5 seconds...");
              try {
                await clientPage.waitForNavigation({ waitUntil: "domcontentloaded", timeout: 5000 });
                console.log("Navigation event detected on the client page.");
              } catch (e) {
                console.warn("No navigation event detected on the client page. Proceeding with a 5-second delay.");
              }

              console.log("Starting a fixed 5-second delay...");
              await new Promise(resolve => setTimeout(resolve, 5000));
              console.log("Delay completed.");

              await clientPage.screenshot({ path: path.join(screenshotsDir, "step6_client_opened.png"), fullPage: true });
              console.log("Client page screenshot captured.");

              // STEP 7: Unmaximize the client window and click the Start button.
              console.log("[DEBUG] Attempting to unmaximize the client window...");

              // 7a) Log current viewport from inside the page.
              let dimsBefore = await clientPage.evaluate(() => ({
                w: window.innerWidth, 
                h: window.innerHeight
              }));
              console.log(`[DEBUG] Current window.innerWidth=${dimsBefore.w}, window.innerHeight=${dimsBefore.h} (before resizing).`);

              // Override screen.availWidth so that the fullscreen check fails.
              console.log("[DEBUG] Overriding window.screen.availWidth to 1920...");
              await clientPage.evaluate(() => {
                Object.defineProperty(window.screen, 'availWidth', {
                  get: () => 1920,
                  configurable: true
                });
                window.dispatchEvent(new Event('resize'));
              });

              // 7b) Set viewport to a smaller size and call window.resizeTo.
              const UNMAX_WIDTH = 800;
              const UNMAX_HEIGHT = 600;
              console.log(`[DEBUG] Setting viewport to ${UNMAX_WIDTH}x${UNMAX_HEIGHT}...`);
              await clientPage.setViewport({ width: UNMAX_WIDTH, height: UNMAX_HEIGHT });

              console.log("[DEBUG] Calling window.resizeTo in page context and dispatching resize event...");
              await clientPage.evaluate((w, h) => {
                window.resizeTo(w, h);
                window.dispatchEvent(new Event('resize'));
              }, UNMAX_WIDTH, UNMAX_HEIGHT);

              // Wait for the page to adjust.
              await new Promise(resolve => setTimeout(resolve, 3000));

              // 7c) Log new viewport dimensions.
              let dimsAfter = await clientPage.evaluate(() => ({
                w: window.innerWidth, 
                h: window.innerHeight
              }));
              console.log(`[DEBUG] After resizing, window.innerWidth=${dimsAfter.w}, window.innerHeight=${dimsAfter.h}.`);

              // 7d) Check whether the "unmaximize window" error is still present.
              const bodyText = await clientPage.evaluate(() => document.body.innerText || "");
              if (bodyText.includes("Please unmaximize the client window")) {
                console.warn("[DEBUG] The 'unmaximize window' error text is still present in the page.");
                console.warn("[DEBUG] Error snippet:", bodyText.substr(bodyText.indexOf("Please unmaximize"), 200));
                const errorHtml = await clientPage.content();
                fs.writeFileSync(path.join(screenshotsDir, "step7_unmaximized_error.html"), errorHtml);
                console.warn("[DEBUG] Saved HTML content for unmaximize error to step7_unmaximized_error.html.");
              } else {
                console.log("[DEBUG] The 'unmaximize window' error text was not found in the document body.");
              }
              
              // Take a screenshot after unmaximize.
              await clientPage.screenshot({ path: path.join(screenshotsDir, "step7_unmaximized.png"), fullPage: true });
              console.log("[DEBUG] Screenshot taken after unmaximize attempt.");

              console.log("Waiting for the Start button to be visible...");
              await clientPage.waitForSelector('#startBtn', { visible: true, timeout: 30000 });
              console.log("Clicking the Start button...");
              await clientPage.click('#startBtn');
              await clientPage.screenshot({ path: path.join(screenshotsDir, "step7_after_start_click.png"), fullPage: true });
              console.log("Start button clicked.");

              // STEP 8: Check for a new window after Start and wait 60 seconds.
              console.log("Waiting 15 seconds to see if a new window opens after Start...");
              const newWindowPromise = new Promise(resolve => {
                let newWindowDetected = false;
                const checkStart = Date.now();
                const maxCheckTime = 15000; // check for 15 seconds

                const listener = async target => {
                  if (target.type() === 'page') {
                    newWindowDetected = true;
                    console.log("New window opened after Start. Waiting 5 seconds for it to adjust...");
                    const popupPage = await target.page();
                    await new Promise(resolve => setTimeout(resolve, 5000));
                    const dims = await popupPage.evaluate(() => ({ width: window.innerWidth, height: window.innerHeight }));
                    console.log("Popup window dimensions:", dims);
                    if (dims.width === 0) {
                      console.warn("Popup width is 0. Forcing viewport to 800x600...");
                      await popupPage.setViewport({ width: 800, height: 600 });
                    }
                    console.log("Taking screenshot of popup window...");
                    await popupPage.screenshot({ path: path.join(screenshotsDir, "step8_new_window_after_start.png"), fullPage: true });
                    if (typeof browser.removeListener === 'function') {
                      browser.removeListener('targetcreated', listener);
                    } else if (typeof browser.off === 'function') {
                      browser.off('targetcreated', listener);
                    }
                    resolve();
                  }
                };

                browser.on('targetcreated', listener);

                const interval = setInterval(() => {
                  if (Date.now() - checkStart >= maxCheckTime) {
                    clearInterval(interval);
                    if (typeof browser.removeListener === 'function') {
                      browser.removeListener('targetcreated', listener);
                    } else if (typeof browser.off === 'function') {
                      browser.off('targetcreated', listener);
                    }
                    if (!newWindowDetected) {
                      console.log("No new window was detected within 15 seconds after Start.");
                    }
                    resolve();
                  }
                }, 500);
              });
              await newWindowPromise;

              console.log("Waiting 60 seconds after Start for any progress or changes...");
              await new Promise(resolve => setTimeout(resolve, 60000));
              await clientPage.screenshot({ path: path.join(screenshotsDir, "step8_after_60secs.png"), fullPage: true });
              console.log("60-second wait completed. Final screenshot captured.");

            } catch (error) {
              console.error("An error occurred during the process:", error.message);
              try {
                const errorHtml = await page.content();
                fs.writeFileSync(path.join(screenshotsDir, "error_page.html"), errorHtml);
                await page.screenshot({ path: path.join(screenshotsDir, "error.png"), fullPage: true });
                console.error("[DEBUG] Saved error HTML to error_page.html.");
              } catch (_) {}
              process.exit(1);
            } finally {
              await browser.close();
            }
          })();
          EOL

      - name: Run YTMonster Login and Launch Script
        run: |
          echo "Running YTMonster login and launch client script..."
          node scripts/ytmonster-login.js | tee script_output.log

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ytmonster-debug-artifacts
          path: |
            screenshots/
            script_output.log
